name: test_ios_14

on:
  push:
    branches:
      - test/ios-14/helloworld

jobs:
  build:
    runs-on: macOS-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: disbale report crash
        run: |
          launchctl unload -w /System/Library/LaunchAgents/com.apple.ReportCrash.plist
          sudo launchctl unload -w /System/Library/LaunchDaemons/com.apple.ReportCrash.Root.plist

      - uses: actions/checkout@v2

      - name: Set up Node JS 10.17.0
        uses: actions/setup-node@v1
        with:
          node-version: '10.17.0'

      - name: Clean Packages
        run: |
          rm -rf node_modules
          npm cache clean --force
          rm -rf package-lock.json

      - name: Install React Native CLI
        run: |
          npm install react-native-cli

      - name: List iOS Devices & Platforms
        run: |
          xcrun simctl list

      - name: Install iOS 14.1 Runtime
        run: |
          gem install xcode-install
          xcversion simulators --install='iOS 14.1'

      - name: Create and Run iOS Emulator - iPhoneX on iOS 14.1, Update default appium config for iOS
        run: |
          xcrun simctl create TestiPhoneX com.apple.CoreSimulator.SimDeviceType.iPhone-X com.apple.CoreSimulator.SimRuntime.iOS-14-1 > deviceid.txt
          DEVICEUUID=`cat deviceid.txt`
          echo $DEVICEUUID
          xcrun simctl boot $DEVICEUUID &

      - name: Use HTTPS repos
        run: |
          git config --global url."https://github".insteadOf ssh://git@github

      - name: Install Repo and Dependencies
        continue-on-error: true
        run: |
          brew install ffmpeg

          cd github-actions-ios-emulator-tryout
            npm install --save-dev
            npm install appium-doctor
            ./node_modules/.bin/appium-doctor
          cd -

      # Start the Appium Server
      - name: Start the Appium Server
        continue-on-error: true
        run: |
          cd github-actions-ios-emulator-tryout
            ./node_modules/.bin/appium --log-timestamp --log-no-colors --allow-insecure chromedriver_autodownload > appium.log &
          cd -

      - name: Poll for Appium Server to Start
        run: |
          sleep 60

      - name: check python version
        continue-on-error: true
        run: |
          python3 -V
          python3 -m pip install pip --upgrade
          python3 -m pip install pipenv
          pipenv --version

      - name: python appium test
        continue-on-error: true
        run: |
          cd github-actions-ios-emulator-tryout
            echo 'start python appium test'
            pipenv sync
            pipenv run python -m pytest --html=output_ios14/index.html test_ios14.py

            ls -la

          cd -

      - name: update result
        continue-on-error: true
        env:
          LOUISCKLAW_GITHUB_TOKEN: ${{ secrets.LOUISCKLAW_GITHUB_TOKEN }}
        run: |
          git config --global user.email "louiscklaw@gmail.com"
          git config --global user.name "louiscklaw"
          git clone https://louiscklaw:$LOUISCKLAW_GITHUB_TOKEN@github.com/LynkedKK/QA_test_result.git --branch=master QA_test_result

          cp -r github-actions-ios-emulator-tryout/output_ios14/  QA_test_result/ios14

          ls -l QA_test_result

          cd QA_test_result
            git add .
            git commit -m"update routine result from ios14,"
            git push

      - name: Upload Test Results
        continue-on-error: true
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: |
            github-actions-ios-emulator-tryout/expected
            github-actions-ios-emulator-tryout/actual

      - name: Upload Test Results
        continue-on-error: true
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: |
            github-actions-ios-emulator-tryout/*.log
