name: test_ios_12

on:
  push:
    branches:
      - test/ios-12/helloworld

jobs:
  build:
    runs-on: macOS-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: disbale report crash
        run: |
          launchctl unload -w /System/Library/LaunchAgents/com.apple.ReportCrash.plist
          sudo launchctl unload -w /System/Library/LaunchDaemons/com.apple.ReportCrash.Root.plist

      - uses: actions/checkout@v2

      - name: Clean Packages
        run: |
          cd src
            pipenv run python -m pytest --json-report --json-report-file=test_IOS12.json --html=./output_ios12/index.html test_json_metadata.py
          cd -