name: test_ios_14

on:
  push:
    branches:
      - test/update-result/**

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - name: update result
        env:
          LOUISCKLAW_GITHUB_TOKEN: ${{ secrets.LOUISCKLAW_GITHUB_TOKEN }}
        run: |
          git config --global user.email "louiscklaw@gmail.com"
          git config --global user.name "louiscklaw"
          git clone https://louiscklaw:$LOUISCKLAW_GITHUB_TOKEN@github.com/LynkedKK/QA_test_result.git --branch=master QA_test_result

          rsync -avzh --progress reports/functional/*  QA_test_result/ios_results

          ls -l QA_test_result

          cd QA_test_result
            git add .
            git commit -m"update routine result,"
            git push
