name: test_ios_14

on:
  push:
    branches:
      - test/upload-result/helloworld

  schedule:
    - cron:  '0 */1 * * *	'

jobs:
  build:
    runs-on: macOS-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: python appium test
        continue-on-error: true
        run: |
          pwd
          ls -l
          cd github-actions-ios-emulator-tryout
            echo helloworld > output_ios12/helloworld.html

            ls -la

          cd -

      - name: update result
        continue-on-error: true
        env:
          LOUISCKLAW_GITHUB_TOKEN: ${{ secrets.LOUISCKLAW_GITHUB_TOKEN }}
        run: |
          git config --global user.email "louiscklaw@gmail.com"
          git config --global user.name "louiscklaw"
          git clone https://louiscklaw:$LOUISCKLAW_GITHUB_TOKEN@github.com/LynkedKK/QA_test_result.git --branch=master QA_test_result

          cp -r github-actions-ios-emulator-tryout/output_ios12/  QA_test_result/ios12

          ls -l QA_test_result

          cd QA_test_result
            git add .
            git commit -m"update routine result from ios12 helloworld,"
            git push
